import json, io
from util import get_auth
from util import load_json
from util import save_json
import twitter
from robust_request import make_twitter_request
import sys


def main():
    """
    Gets propagandists information given the propagandists user id
    """
    #File containing the file generated by topsy_parasite.py
    filename =  'propagandists_merged_3000' #sys.argv[1]#'topsy_results/#NoOlvidamosPPSOE_topsy'
    propagandists_ids = load_json(filename)
    #File name for saving the tweets information.
    output_filename = 'propagandists_info_3000'#sys.argv[2]#'tweets/#NoOlvidamosPPSOE'

    user = 'pablo'
    print "user: {0}".format(user)
   
    CONSUMER_KEY, CONSUMER_SECRET, OAUTH_TOKEN, OAUTH_TOKEN_SECRET = get_auth(user)

    auth = twitter.oauth.OAuth(OAUTH_TOKEN, OAUTH_TOKEN_SECRET,
                               CONSUMER_KEY, CONSUMER_SECRET)

    twitter_api = twitter.Twitter(auth=auth)

    propagandists = [None] * len(propagandists_ids)
    errors = 0
    #For each tweet id retrieve the tweet
    for i, p_id in enumerate(propagandists_ids):
        try:
            propagandists[i] = make_twitter_request(twitter_api.users.show, user_id=str(p_id))
            print u"@{0} \t {1} \t <<{2}>>".format(propagandists[i]['screen_name'], propagandists[i]['name'], propagandists[i]['description'])
        except:
            print "ERROR at propagandist number {0} with id {1}".format(i, p_id)
            errors += 1

    print "DONE with {0} errors".format(errors)
    save_json(output_filename, propagandists)


if __name__ == '__main__':
    main()